---
version: '3'
services:
  embedding-service:
    build: 
      dockerfile: Dockerfile
      context: .
    container_name: embeddings_container
    depends_on:
      - mysql-db-embedding-service
    ports:
      - 3002:3002
    volumes:
      - embeddings-data_store:/srv/app
    networks:
      - embedding-network
    environment:
      - PINE_CONE_END-POINT=xyz.com
      - DB_HOST=embedding_db_container
      - MYSQL_USER = admin
      - MYSQL_PASSWORD = root
      - DB_PORT = 3306
      - DB_NAME = EMBEDDING
      - FOLDER_BASE = /srv/UPLOAD/
      - DEPLOYMENT_NAME = KUBER_DEPLOYMENT
      - KUBER_NAMESPACE = KUBER_NAMESPACE
      - CONTAINER_NAME = KUBER_CONTAINER

  mysql-db-embedding-service:
    image: mysql
    container_name: embedding_db_container
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - embedding-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root 
      - MYSQL_USER=admin
      - MYSQL_DATABASE=EMBEDDING  
  
volumes:
  embeddings-data_store:
  db-data:
networks:
  embedding-network:
